#In order to run InterSensor Service with this YAML file,
#Copy the contents of this file in the file src/main/resources/application.yml

#Optionnal: Configure server port here. 
#If not defined, the default port is 8080

#server:
#  port: 9091

#Provide Thingspeak Channel details here  
#Thingspeak channel consists of a channel id, which further comprises of different fields 
# For example, https://thingspeak.com/channels/64242

datasource-connection:
  name: "Thingspeak_Humidity_Sensor"
  description: "New thingspeak connection recording Humidity"
  connectionType: "Thingspeak"
  observationProperty: "Humidity_Thingspeak"
  unitOfMeasure: "Percent"
  serviceName: "Thingspeak"
  serviceType: "JSON"
  channel: 64242
  field: 2