#In order to run InterSensor Service with this YAML file,
#Copy the contents of this file in the file application.yml

#Optionnal: Configure server port here. 
#If not defined, the default port is 8080

#server:
#  port: 9091

#Provide CSV file details here  
#This example is for retrieving time period details from a csv file 

datasource-connection:
  name: "TwitterConnection"
  description: "GeoTagged Tweets around London QEOP"
  connectionType: "Twitter"
  #observationProperty: "CSV_Events_ArcelorMittal_Orbit"
  observationType: "String"
  unitOfMeasure: "TweetJSON"
  serviceName: "Twitter API"
  serviceType: "JSON"
  baseUrl: "https://api.twitter.com/1.1/search/tweets.json"
  apiKey: "GnYN7GGuOtRXJHe3DfkLpte6F"
  apiSecret: "o3wO1UNUySGld9lXoQMvFWpAKPd8VAkTHu2bEV1b4QkLyjLGXq"
  accessToken: "38715440-q3dLLeHRS2OqQRl0gwijUvlsBipIdxrcUHnK1SK8o"
  accessTokenSecret: "q191jEc1ibF8psoh4QbAIflK8sTarJDVGD6s5iTyXfNTT"
  latitude: 51.54347
  longitude: -0.01652
  radius: 1